"""added age to user

Revision ID: 374bea2aef02
Revises: 5fde54f17606
Create Date: 2021-07-09 13:13:40.726233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '374bea2aef02'
down_revision = '5fde54f17606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'age')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
