"""created News and Users tables

Revision ID: 587bb759a706
Revises: 
Create Date: 2021-09-30 01:31:15.130931

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "587bb759a706"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "news",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("published", sa.String(), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_name", sa.String(length=50), nullable=True),
        sa.Column("password", sa.String(length=128), nullable=True),
        sa.Column("role", sa.String(length=10), nullable=True),
        sa.Column("email", sa.String(length=50), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_user_role"), "user", ["role"], unique=False)
    op.create_index(op.f("ix_user_user_name"), "user", ["user_name"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_user_name"), table_name="user")
    op.drop_index(op.f("ix_user_role"), table_name="user")
    op.drop_table("user")
    op.drop_table("news")
    # ### end Alembic commands ###
